trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:

# Prepare
# Docker
- task: DockerInstaller@0
  displayName: Docker install
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    dockerVersion: 19.03.5
    releaseType: stable
- task: Docker@2
  displayName: Docker registry login
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: login
    containerRegistry: docker_registry
- bash: |
    sudo wget -O /usr/local/bin/buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    sudo chmod a+x /usr/local/bin/buildx
    docker run --rm --privileged hypriot/qemu-register:v2.7.0
    buildx create --use
    buildx ls
  displayName: 'Docker setup'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
- bash: |
    buildx build \
      --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
      --push \
      -t jshridha/inkbird:latest-dev \
      .
  displayName: 'Docker build dev'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'), ne(variables['Build.Reason'], 'PullRequest'))
- bash: |
    TAG="$(git describe --tags)"
    buildx build \
      --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 \
      --push \
      -t jshridha/inkbird:latest -t "jshridha/inkbird:$TAG" \
      .
  displayName: 'Docker build release'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), ne(variables['Build.Reason'], 'PullRequest'))
