version: "3"

services:
  inkbird:
    image: jshridha/inkbird
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - INKBIRD_MQTT_HOST=hass.local
	    - INKBIRD_MQTT_USER=user
      - INKBIRD_MQTT_PASS=password      
      - INKBIRD_ADDRESS=90:70:65:F7:8D:AD
